### ISSUE TITLE
Running the quickstart with default settings doesn't work

### ISSUE THREAD

**Issue by fox2402** [Azure-Samples/batch-dotnet-quickstart#12]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
clones, fills in the keys for account and storage, run

### Any log messages given by the failure "The resource directory path could not be created" on the portal
"Microsoft.Azure.Batch.Common.BatchException: 'Operation returned an invalid status code 'NotFound''" at line 168 on the C#

### Expected/desired behavior
>

### OS and Version?
Win 10 enterprise v1809

### Versions

VS2017 with .NET core v2.1. 
The storage account is LRS and hot with standard. 
The batch account has enough available CPU (it creates the pool without error)

**Comment by matthchr** [comment]
@laurenhughes - can you or Julia take a look at this?

**Comment by matthchr** [comment]
@ju-shim

**Comment by ju-shim** [comment]
#please-close

**Comment by ju-shim** [comment]
#reassign: @ju-shim

**Comment by ju-shim** [comment]
@matthchr - This is an outdated request and we only have new writers on Batch. I'm trying to do some clean up and close outdated issues, but because this is the samples repo - I can't apply any automation to close this out. Do you have links to instructions on how to assign or close issues in this repo? Or do you mind closing this out on our behalf? Thank you.
